### ISSUE TITLE
I recieved a SIARDDK dataset.  What tools can I use to convert this to SQL?

### ISSUE THREAD

**Issue by rh0dium** [eark-project/siard-2-format#2]
Hi Folks,

I received what I beleive to be a SIARDK dataset.  I need to convert this back to SQL.  Can anyone point me to a tool or tools which do this?  I'd be willing to pay for this service if needed.

Thanks so much,

<img width="1441" alt="archiveindex_xml_-_marc_cr_-____development_7stalks_marccr_db_work_" src="https://cloud.githubusercontent.com/assets/170789/10791983/063f5374-7d48-11e5-8083-0ba317e304a5.png">

**Comment by luis100** [comment]
@rh0dium the tool for that work would be the [database preservation toolkit](https://github.com/keeps/db-preservation-toolkit)

We, KEEP SOLUTIONS and Magenta, on the EARK project, are currently developing a version that supports all versions of SIARD. Unfortunately, although the system already supports input and output of SIARD 1.0 and SIARD 2.0 (except for LOBS and UDTs), it only support output of SIARD DK format (no input).

The tool also supports import and export to several relational database systems, via JDBC, where the you could convert to SQL if you would like to.

So, sorry I cannot give you a final solution, we are still trying to find resources to develop the SIARD DK input module, but can't promise this will be a priority on the research project.

**Comment by rh0dium** [comment]
Luis,

Thanks so much for your fast reply.  I appears the differences between SIARD and SIARD DK are relatively small.  How can I confirm the format is in fact SIARD DK?  I based my conclusion on the `http://www.sa.dk/xmlns/diark/1.0` located in most of the headers but I'm not sure?

Can you point me in the right direction on this?

Thanks

**Comment by luis100** [comment]
The namespace seems to indicate that it is a SIARD DK format, but they are really alike. Main differences on the metadata could be fixed manually, and then you could use the database preservation toolkit to try to import the database to a DBMS like PostgreSQL or MySQL.

The [KOST-Val tool](https://github.com/KOST-CECO/KOST-Val) allows you to validate the SIARD against 1.0 spec. You could check the [metadata mapping](https://github.com/eark-project/siard-e-format/blob/master/SIARDDK/SIARD-SIARDDK_metadatamapping.xlsx) to see how to convert one into the other. After getting a SIARD 1.0 valid document, you could use the database preservation toolkit to import it to a DBMS.

**Comment by HartwigThomas** [comment]
As far as I know, the difference between SIARD and SIARDDK are not quite so small. It would be best, to ask Anders Bo Nielsen ...
Hartwig

-----Ursprüngliche Nachricht-----
Von: Steven [mailto:notifications@github.com] 
Gesendet: Mittwoch, 28. Oktober 2015 16:04
An: eark-project/siard-e-format
Betreff: Re: [siard-e-format] I recieved a SIARDDK dataset. What tools can I use to convert this to SQL? (#2)

Luis,

Thanks so much for your fast reply. I appears the differences between SIARD and SIARD DK are relatively small. How can I confirm the format is in fact SIARD DK? I based my conclusion on the http://www.sa.dk/xmlns/diark/1.0 located in most of the headers but I'm not sure?

Can you point me in the right direction on this?

Thanks
